### ISSUE TITLE
Code about the HDP process.

### ISSUE THREAD

**Issue by lincj1994** [Rashesh7/PanBody_manuscript_analyses#1]
HI. I cannot find the code about the Hierarchical Dirichlet Process in your repository.

**Comment by Rashesh7** [comment]
Hi,
Sorry I missed this and about the delay. I will upload the code for HDP analyses by early next week. HDP is a bit more hands-on than compared to SigProfiler. I will upload the scripts with a bit more comments, so it is easier to follow the flow.

**Comment by laurelhiatt** [comment]
Hi, I was also wondering if you could post the HDP code, as I was hoping to use it as reference in some meta sig comparisons. Thanks.

**Comment by Rashesh7** [comment]
Hello,

I am extremely sorry about this. I don't know why these emails when to
another folder. I will upload the scripts first thing tomorrow morning.

Many thanks,
Rashesh

**Comment by laurelhiatt** [comment]
Thank you Rashesh! No worries at all. I too have been betrayed by email.

**Comment by Rashesh7** [comment]
Hi, 
You can use and follow the same process as described in 
https://github.com/TimCoorens/Polymerase/tree/master/Signatures 
I have also used the same scripts, just adapted to this dataset. 
Do let me know if that is fine and works.

**Comment by laurelhiatt** [comment]
Gotcha, I will use those as a reference, thank you so much!
